# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

# a1 = Album.create(cover: "http://s3.amazonaws.com/codecademy-content/projects/3/bass-music/my-beautiful-dark-twisted-fantasy.jpg", title: "My Beautiful Dark Twisted Fantasy", artist: "Kanye West", release_year: 2010)
# Track.create(name: "Dark Fantasy",  album_id: a1.id)
# Track.create(name: "Gorgeous",  album_id: a1.id)
# Track.create(name: "Power",  album_id: a1.id)
# Track.create(name: "All of the Lights",  album_id: a1.id)
# Track.create(name: "Monster",  album_id: a1.id)
# Track.create(name: "So Appalled",  album_id: a1.id)
# Track.create(name: "Devil in a New Dress",  album_id: a1.id)
# Track.create(name: "Runaway",  album_id: a1.id)
# Track.create(name: "Hell of a Life",  album_id: a1.id)
# Track.create(name: "Blame Game",  album_id: a1.id)
# Track.create(name: "Lost in the World", album_id: a1.id)
# Track.create(name: "Who will Survive in America",  album_id: a1.id)

a2 = Album.create(cover: "http://s3.amazonaws.com/codecademy-content/projects/3/bass-music/beyonce.png", title: "Beyonce", artist: "Beyonce", release_year: 2010)
Track.create(name: "Pretty Hurts",  album_id: a2.id)
Track.create(name: "Haunted",  album_id: a2.id)
Track.create(name: "Drunk in Love",  album_id: a2.id)
Track.create(name: "Blow",  album_id: a2.id)
Track.create(name: "No Angel",  album_id: a2.id)
Track.create(name: "Partition",  album_id: a2.id)
Track.create(name: "Jealous",  album_id: a2.id)
Track.create(name: "Rocket",  album_id: a2.id)
Track.create(name: "Mine",  album_id: a2.id)
Track.create(name: "XO",  album_id: a2.id)
Track.create(name: "Flawless",  album_id: a2.id)
Track.create(name: "Superpower",  album_id: a2.id)
Track.create(name: "Heaven",  album_id: a2.id)
Track.create(name: "Blue",  album_id: a2.id)

a3 = Album.create(cover: "http://s3.amazonaws.com/codecademy-content/projects/3/bass-music/21.png", title: "21", artist: "Adele", release_year: 2010)
Track.create(name: "Rolling in the Deep", album_id: a3.id)
Track.create(name: "Rumour Has It",  album_id: a3.id)
Track.create(name: "Turning Tables",  album_id: a3.id)
Track.create(name: "Don't You Remember",  album_id: a3.id)
Track.create(name: "Set Fire to the Rain",album_id: a3.id)
Track.create(name: "He Won't Go",  album_id: a3.id)
Track.create(name: "Take it All",  album_id: a3.id)
Track.create(name: "I'll be Waiting",  album_id: a3.id)
Track.create(name: "One and Only",  album_id: a3.id)
Track.create(name: "Lovesong",  album_id: a3.id)

a4 = Album.create(cover: "http://s3.amazonaws.com/codecademy-content/projects/3/bass-music/channel-orange.jpg", title: "Channel Orange", artist: "Frank Ocean", release_year: 2010)
Track.create(name: "Start",  album_id: a4.id)
Track.create(name: "Thinkin Bout You",  album_id: a4.id)
Track.create(name: "Fertilizer",  album_id: a4.id)
Track.create(name: "Sierra Leone",  album_id: a4.id)
Track.create(name: "Sweet Life",  album_id: a4.id)
Track.create(name: "Not Just Money",  album_id: a4.id)
Track.create(name: "Super Rich Kids",  album_id: a4.id)
Track.create(name: "Pilot Jones",  album_id: a4.id)
Track.create(name: "Crack Rock",  album_id: a4.id)
Track.create(name: "Pyramids",  album_id: a4.id)
Track.create(name: "Lost",  album_id: a4.id)
Track.create(name: "White",  album_id: a4.id)
Track.create(name: "Monks",  album_id: a4.id)
Track.create(name: "Bad Religion",  album_id: a4.id)
Track.create(name: "Pink Matter",  album_id: a4.id)
Track.create(name: "Forrest Gump",  album_id: a4.id)
Track.create(name: "End/Golden Girl",  album_id: a4.id)

a5 = Album.create(cover: "http://s3.amazonaws.com/codecademy-content/projects/3/bass-music/good-kid-maad-city.jpg", title: "Good Kid, M.A.A.D City", artist: "Kendrick Lamar", release_year: 2010)
Track.create(name: "Sherane a.k.a. Master Splinters Daughter",  album_id: a5.id)
Track.create(name: "Bitch, Don't Kill My Vibe",  album_id: a5.id)
Track.create(name: "Backseat Freestyle",  album_id: a5.id)
Track.create(name: "The Art of Peer Pressure",  album_id: a5.id)
Track.create(name: "Money Trees",  album_id: a5.id)
Track.create(name: "Poetic Justice",  album_id: a5.id)
Track.create(name: "good kid",  album_id: a5.id)
Track.create(name: "m.A.A.d city",  album_id: a5.id)
Track.create(name: "Swimming Pools (Drank)",  album_id: a5.id)
Track.create(name: "Sing About Me, Im Dying of Thirst",  album_id: a5.id)
Track.create(name: "Real",  album_id: a5.id)
Track.create(name: "Compton",  album_id: a5.id)

a6 = Album.create(cover: "http://s3.amazonaws.com/codecademy-content/projects/3/bass-music/ram.jpg", title: "Random Access Memories", artist: "Daft Punk", release_year: 2010)
Track.create(name: "Give Life Back to Music",  album_id: a6.id)
Track.create(name: "The Game of Love",  album_id: a6.id)
Track.create(name: "Giorgio by Moroder",  album_id: a6.id)
Track.create(name: "Within",  album_id: a6.id)
Track.create(name: "Instant Crush",  album_id: a6.id)
Track.create(name: "Lose Yourself to Dance",  album_id: a6.id)
Track.create(name: "Touch", album_id: a6.id)
Track.create(name: "Get Lucky",  album_id: a6.id)
Track.create(name: "Beyond",  album_id: a6.id)
Track.create(name: "Motherboard",  album_id: a6.id)
Track.create(name: "Fragments of Time",  album_id: a6.id)
Track.create(name: "Doin' It Right",  album_id: a6.id)
Track.create(name: "Contact",  album_id: a6.id)

a7 = Album.create(cover: "http://s3.amazonaws.com/codecademy-content/projects/3/bass-music/the-2020-experience.png", title: "The 20/20 Experience", artist: "Justin Timberlake", release_year: 2010)
Track.create(name: "Pusher Love Girl",  album_id: a7.id)
Track.create(name: "Suit & Tie",  album_id: a7.id)
Track.create(name: "Don't Hold the Wall",  album_id: a7.id)
Track.create(name: "Strawberry Bubblegum",  album_id: a7.id)
Track.create(name: "Tunnel Vision",  album_id: a7.id)
Track.create(name: "Spaceship Coupe",  album_id: a7.id)
Track.create(name: "That Girl",  album_id: a7.id)
Track.create(name: "Let the Groove Get In",  album_id: a7.id)
Track.create(name: "Mirrors",  album_id: a7.id)
Track.create(name: "Blue Ocean Floor",  album_id: a7.id)